# Generated by Django 4.1 on 2022-08-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buguer', '0003_alter_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
