# Generated by Django 4.1 on 2022-08-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buguer', '0005_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.TextField(default=''),
        ),
    ]
